:datasets:
  - :dataset: skymapper
    :description: TODO
    :catalogues:
      - :catalogue: fs
        :description: TODO
        :services:
          - :service: TAP
            :description: TODO
            :service_end_point: http://astroa.anu.edu.au:8080/skymapperpublic-asov-tap/tap
            :table_name: public.fs_distilled
            :fields:
              :ra_field:
                :field: mean_ra
                :name: Right ascension
              :dec_field:
                :field: mean_dcl
                :name: Declination
              :object_id_field:
                :field: global_object_id
                :name: Object Id
              :u_field:
                :field: flux_u
                :name: U
              :v_field:
                :field: flux_v
                :name: V
              :g_field:
                :field: flux_g
                :name: G
              :r_field:
                :field: flux_r
                :name: R
              :i_field:
                :field: flux_i
                :name: I
              :z_field:
                :field: flux_z
                :name: Z
      - :catalogue: ms
        :description: TODO
        :services:
          - :service: TAP
            :description: TODO
            :service_end_point: http://astroa.anu.edu.au:8080/skymapperpublic-asov-tap/tap
            :table_name: public.ms_distilled
            :fields:
              :ra_field:
                :field: ra
                :name: Right ascension
              :dec_field:
                :field: dcl
                :name: Declination
              :object_id_field:
                :field: new_object_id
                :name: Object Id
              :u_field:
                :field: mean_u
                :name: U
              :v_field:
                :field: mean_v
                :name: V
              :g_field:
                :field: mean_g
                :name: G
              :r_field:
                :field: mean_r
                :name: R
              :i_field:
                :field: mean_i
                :name: I
              :z_field:
                :field: mean_z
                :name: Z
      - :catalogue: image
        :description: TODO
        :services:
          - :service: SIAP
            :description: TODO
            :service_end_point: http://astroa.anu.edu.au/skymapper/image_siap/siap
            :fields:
              :ra_field:
                :field: POINTRA_DEG
                :name: Right ascension
              :dec_field:
                :field: POINTDEC_DEG
                :name: Declination
              :filter_field:
                :field: FILTER
                :name: Filter
              :survey_field:
                :field: IMAGE_TYPE
                :name: Survey
              :observation_date_field:
                :field: DATE
                :name: Observation Date (MJD)
              :image_url:
                :field: ACCESSURL
                :name: Image URL
  - :dataset: wigglez
    :description: TODO
