datasets:
  - dataset: skymapper
    description: TODO
    catalogues:
      - catalogue: fs
        description: TODO
        service: TAP
        service_end_point: http://astroa.anu.edu.au:8080/skymapperpublic-asov-tap/tap
        table_name: public.fs_distilled
        ra_column_name: mean_ra
        dec_column_name: mean_dcl
  - dataset: wigglez
    description: TODO
